apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: h3uidha9q-dotnet-basic
  janus-idp.io/tekton: h3uidha9q-dotnet-basic
  backstage.io/kubernetes-id: h3uidha9q-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h3uidha9q-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
